sudo: required
language: cpp
compiler: gcc-5
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libegl1-mesa-dev
  - sudo apt-get install -y libgles2-mesa-dev
  - sudo apt-get install -y libsdl2-dev
  - sudo apt-get install -y libsdl2-image-dev
  - sudo apt-get install -y libsdl2-ttf-dev
script:
  - make fedora
